### ISSUE TITLE
Incorrect file path

### ISSUE THREAD

**Issue by jim-rosales** [Xcifan/Dosmotos-Art-and-Crafts#3]
You did an excellent job using relative paths! The only issue is you don't have a resources folder in your repo.

This caused your project to be rendered in the following way:
![screen shot 2018-03-09 at 2 41 12 pm](https://user-images.githubusercontent.com/28379087/37233450-13c5f72e-23a8-11e8-8f92-61213381e916.png)

Since you don't have a resource folder in your repo the correct path would be the following:
```HTML
<link href="style.css" type="text/css" rel="stylesheet">
```

https://github.com/Xcifan/Dosmotos-Art-and-Crafts/blob/560712d7db536cb8dcc9efad08943c335b3f775b/index.html#L7

**Comment by Xcifan** [comment]
Relative path has been corrected.
