### ISSUE TITLE
Ampersand symbol

### ISSUE THREAD

**Issue by jim-rosales** [Xcifan/Dosmotos-Art-and-Crafts#4]
If you take a look at the ampersand symbol below it is currently highlighted in red. The reason for this is because it is a reserved character in HTML to add special characters via their [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). 

Since it is a reserved character the correct method for adding an ampersand symbol is by replacing `&` by `&amp;`

https://github.com/Xcifan/Dosmotos-Art-and-Crafts/blob/560712d7db536cb8dcc9efad08943c335b3f775b/index.html#L13

**Comment by Xcifan** [comment]
Syntax error has been changed.
